spring:
  application:
    name: Coordinator

zookeeper:
  hosts: ${ZK_QUORUM}
  connection:
    retries: 3
    timeoutMS: 5000
  session:
    timeoutMS: 60000
  cache:
    instancesTimeoutMS: 60000

---
spring:
  profiles: development

zookeeper:
  hosts: localhost:2181
